---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: payment-state-query
  labels:
    run: payment-state-query
spec:
  replicas: 1
  selector:
    matchLabels:
      run: payment-state-query
  template:
    metadata:
      creationTimestamp:
      labels:
        run: payment-state-query
    spec:
      containers:
      - name: payment-state-query
        image: payment-state-query:v1
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: payment-state-query
  labels:
    run: payment-state-query
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30172
  selector:
    run: payment-state-query
  type: LoadBalancer
